# Game Plan

1. Check reports.txt
2. Check report_drug.txt
3. See if they link

In [2]:
# Import libraries

import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_columns', 1000)

data_dir = 'cvponline_extract_20190930'

## 1. Reports.txt

In [5]:
reports = pd.read_csv(data_dir + '/reports.txt', 
                      delimiter='$', 
                      header=None, 
                      names=['REPORT_NO','E2B_IMP_SAFETYREPORT_ID','VERSION_NO','DATRECEIVED','DATINTRECEIVED','MAH_NO','REPORT_TYPE_CODE','REPORT_TYPE_ENG','REPORT_TYPE_FR','GENDER_CODE','GENDER_ENG','GENDER_FR','AGE','AGE_Y','AGE_UNIT_ENG','AGE_UNIT_FR','OUTCOME_CODE','OUTCOME_ENG','OUTCOME_FR','WEIGHT','WEIGHT_UNIT_ENG','WEIGHT_UNIT_FR','HEIGHT','HEIGHT_UNIT_ENG','HEIGHT_UNIT_FR','SERIOUSNESS_CODE','SERIOUSNESS_ENG','SERIOUSNESS_FR','DEATH','DISABILITY','CONGENITAL_ANOMALY','LIFE_THREATENING','HOSP_REQUIRED','OTHER_MEDICALLY_IMP_COND','REPORTER_TYPE_ENG','REPORTER_TYPE_FR','SOURCE_CODE','SOURCE_ENG','SOURCE_FR','UNKNOWN_1','UNKNOWN_2','UNKNOWN_3'],
                      dtype={'REPORT_NO': 'object', 'E2B_IMP_SAFETYREPORT_ID': 'object', 'VERSION_NO': 'int64', 'MAH_NO': 'object', 'REPORT_TYPE_CODE': 'object', 'REPORT_TYPE_ENG': 'object', 'REPORT_TYPE_FR': 'object', 'GENDER_CODE': 'object', 'GENDER_ENG': 'object', 'GENDER_FR': 'object', 'AGE': 'float64', 'AGE_Y': 'float64', 'AGE_UNIT_ENG': 'object', 'AGE_UNIT_FR': 'object', 'OUTCOME_CODE': 'object', 'OUTCOME_ENG': 'object', 'OUTCOME_FR': 'object', 'WEIGHT': 'float64', 'WEIGHT_UNIT_ENG': 'object', 'WEIGHT_UNIT_FR': 'object', 'HEIGHT': 'float64', 'HEIGHT_UNIT_ENG': 'object', 'HEIGHT_UNIT_FR': 'object', 'SERIOUSNESS_CODE': 'object', 'SERIOUSNESS_ENG': 'object', 'SERIOUSNESS_FR': 'object', 'DEATH': 'object', 'DISABILITY': 'object', 'CONGENITAL_ANOMALY': 'object', 'LIFE_THREATENING': 'object', 'HOSP_REQUIRED': 'object', 'OTHER_MEDICALLY_IMP_COND': 'object', 'REPORTER_TYPE_ENG': 'object', 'REPORTER_TYPE_FR': 'object', 'SOURCE_CODE': 'object', 'SOURCE_ENG': 'object', 'SOURCE_FR': 'object', 'UNKNOWN_1': 'object', 'UNKNOWN_2': 'object', 'UNKNOWN_3': 'object'},
                      parse_dates=['DATRECEIVED','DATINTRECEIVED']
                     )

In [6]:
reports.dtypes

REPORT_NO                           object
E2B_IMP_SAFETYREPORT_ID             object
VERSION_NO                           int64
DATRECEIVED                 datetime64[ns]
DATINTRECEIVED              datetime64[ns]
MAH_NO                              object
REPORT_TYPE_CODE                    object
REPORT_TYPE_ENG                     object
REPORT_TYPE_FR                      object
GENDER_CODE                         object
GENDER_ENG                          object
GENDER_FR                           object
AGE                                float64
AGE_Y                              float64
AGE_UNIT_ENG                        object
AGE_UNIT_FR                         object
OUTCOME_CODE                        object
OUTCOME_ENG                         object
OUTCOME_FR                          object
WEIGHT                             float64
WEIGHT_UNIT_ENG                     object
WEIGHT_UNIT_FR                      object
HEIGHT                             float64
HEIGHT_UNIT_ENG                     object
HEIGHT_UNIT_FR                      object
SERIOUSNESS_CODE                    object
SERIOUSNESS_ENG                     object
SERIOUSNESS_FR                      object
DEATH                               object
DISABILITY                          object
CONGENITAL_ANOMALY                  object
LIFE_THREATENING                    object
HOSP_REQUIRED                       object
OTHER_MEDICALLY_IMP_COND            object
REPORTER_TYPE_ENG                   object
REPORTER_TYPE_FR                    object
SOURCE_CODE                         object
SOURCE_ENG                          object
SOURCE_FR                           object
UNKNOWN_1                           object
UNKNOWN_2                           object
UNKNOWN_3                           object
dtype: object

In [7]:
reports.nunique()

REPORT_NO                   751171
E2B_IMP_SAFETYREPORT_ID     751171
VERSION_NO                      85
DATRECEIVED                  14090
DATINTRECEIVED               14058
MAH_NO                      492861
REPORT_TYPE_CODE                 7
REPORT_TYPE_ENG                  7
REPORT_TYPE_FR                   7
GENDER_CODE                      4
GENDER_ENG                       2
GENDER_FR                        2
AGE                            650
AGE_Y                          861
AGE_UNIT_ENG                     6
AGE_UNIT_FR                      6
OUTCOME_CODE                     7
OUTCOME_ENG                      6
OUTCOME_FR                       6
WEIGHT                        3915
WEIGHT_UNIT_ENG                  4
WEIGHT_UNIT_FR                   4
HEIGHT                         888
HEIGHT_UNIT_ENG                  2
HEIGHT_UNIT_FR                   2
SERIOUSNESS_CODE                 2
SERIOUSNESS_ENG                  2
SERIOUSNESS_FR                   2
DEATH                            2
DISABILITY                       2
CONGENITAL_ANOMALY               2
LIFE_THREATENING                 2
HOSP_REQUIRED                    2
OTHER_MEDICALLY_IMP_COND         2
REPORTER_TYPE_ENG                6
REPORTER_TYPE_FR                 6
SOURCE_CODE                      5
SOURCE_ENG                       5
SOURCE_FR                        5
UNKNOWN_1                   283060
UNKNOWN_2                   241144
UNKNOWN_3                   275018
dtype: int64

In [8]:
reports.tail(3)

,REPORT_NO,E2B_IMP_SAFETYREPORT_ID,VERSION_NO,DATRECEIVED,DATINTRECEIVED,MAH_NO,REPORT_TYPE_CODE,REPORT_TYPE_ENG,REPORT_TYPE_FR,GENDER_CODE,GENDER_ENG,GENDER_FR,AGE,AGE_Y,AGE_UNIT_ENG,AGE_UNIT_FR,OUTCOME_CODE,OUTCOME_ENG,OUTCOME_FR,WEIGHT,WEIGHT_UNIT_ENG,WEIGHT_UNIT_FR,HEIGHT,HEIGHT_UNIT_ENG,HEIGHT_UNIT_FR,SERIOUSNESS_CODE,SERIOUSNESS_ENG,SERIOUSNESS_FR,DEATH,DISABILITY,CONGENITAL_ANOMALY,LIFE_THREATENING,HOSP_REQUIRED,OTHER_MEDICALLY_IMP_COND,REPORTER_TYPE_ENG,REPORTER_TYPE_FR,SOURCE_CODE,SOURCE_ENG,SOURCE_FR,UNKNOWN_1,UNKNOWN_2,UNKNOWN_3
751168,902816047,E2B_02816047,0,2019-09-30,2019-09-30,2019BI00790828,8,Study,Étude,2,Female,Fèminin,61.0,61.0,Years,Annèes,09,Not recovered/not resolved,Non rètabli/Non rèsolu,NaN,NaN,NaN,NaN,NaN,NaN,02,Not Serious,Non grave,2,2,2,2,2,2,Consumer/other non health professional,Consommateur/autre non-professionnel de santé,02,Clinical Study,Essai Clinique,CA-BIOGEN-2019BI00790828,NaN,CA-BIOGEN-2019BI00790828
751169,902816049,E2B_02816049,0,2019-09-30,2019-09-30,19K-028-2941849-00,8,Study,Étude,2,Female,Fèminin,73.0,73.0,Years,Annèes,09,Not recovered/not resolved,Non rètabli/Non rèsolu,NaN,NaN,NaN,NaN,NaN,NaN,02,Not Serious,Non grave,2,2,2,2,2,2,Consumer/other non health professional,Consommateur/autre non-professionnel de santé,02,Clinical Study,Essai Clinique,CA-ABBVIE-19K-028-2941849-00,NaN,CA-ABBVIE-19K-028-2941849-00
751170,902816051,E2B_02816051,0,2019-09-30,2019-09-30,2019TUS054574,8,Study,Étude,2,Female,Fèminin,79.0,79.0,Years,Annèes,06,Unknown,Inconnue,NaN,NaN,NaN,NaN,NaN,NaN,02,Not Serious,Non grave,2,2,2,2,2,2,Consumer/other non health professional,Consommateur/autre non-professionnel de santé,02,Clinical Study,Essai Clinique,CA-TAKEDA-2019TUS054574,NaN,CA-TAKEDA-2019TUS054574

In [9]:
reports.describe()

,VERSION_NO,AGE,AGE_Y,WEIGHT,HEIGHT
count,751171.000000,584231.000000,606230.000000,199255.000000,115509.000000
mean,0.628383,52.069545,50.972640,85.295151,140.893568
std,2.444907,21.779405,21.217343,44.216399,44.043639
min,0.000000,-62.000000,-62.000000,0.003000,1.000000
25%,0.000000,38.000000,36.000000,60.000000,117.000000
50%,0.000000,54.000000,54.000000,74.200000,160.000000
75%,0.000000,67.000000,67.000000,96.000000,170.000000
max,99.000000,985.000000,119.000000,1906.000000,292.000000

In [10]:
# count of values in each column

countPerCol = reports.count(axis=0)
fillRatePerCol = reports.count(axis=0)/reports.REPORT_NO.count()

reportsFillRate = pd.concat([countPerCol, fillRatePerCol], axis=1).reset_index()

reportsFillRate.columns = ['Column','Count','Fill Rate (%)']

reportsFillRate

                      Column   Count  Fill Rate (%)
0                  REPORT_NO  751171       1.000000
1    E2B_IMP_SAFETYREPORT_ID  751171       1.000000
2                 VERSION_NO  751171       1.000000
3                DATRECEIVED  751171       1.000000
4             DATINTRECEIVED  751170       0.999999
5                     MAH_NO  511843       0.681393
6           REPORT_TYPE_CODE  751167       0.999995
7            REPORT_TYPE_ENG  751167       0.999995
8             REPORT_TYPE_FR  751167       0.999995
9                GENDER_CODE  732858       0.975621
10                GENDER_ENG  709664       0.944744
11                 GENDER_FR  709664       0.944744
12                       AGE  584231       0.777760
13                     AGE_Y  606230       0.807047
14              AGE_UNIT_ENG  584174       0.777684
15               AGE_UNIT_FR  584174       0.777684
16              OUTCOME_CODE  751170       0.999999
17               OUTCOME_ENG  751169       0.999997
18                OUTCOME_FR  751169       0.999997
19                    WEIGHT  199255       0.265259
20           WEIGHT_UNIT_ENG  199276       0.265287
21            WEIGHT_UNIT_FR  199276       0.265287
22                    HEIGHT  115509       0.153772
23           HEIGHT_UNIT_ENG  115516       0.153781
24            HEIGHT_UNIT_FR  115516       0.153781
25          SERIOUSNESS_CODE  751171       1.000000
26           SERIOUSNESS_ENG  751171       1.000000
27            SERIOUSNESS_FR  751171       1.000000
28                     DEATH  312624       0.416182
29                DISABILITY  294044       0.391447
30        CONGENITAL_ANOMALY  284069       0.378168
31          LIFE_THREATENING  296867       0.395206
32             HOSP_REQUIRED  366995       0.488564
33  OTHER_MEDICALLY_IMP_COND  417661       0.556013
34         REPORTER_TYPE_ENG  540445       0.719470
35          REPORTER_TYPE_FR  540445       0.719470
36               SOURCE_CODE  733964       0.977093
37                SOURCE_ENG  733964       0.977093
38                 SOURCE_FR  733964       0.977093
39                 UNKNOWN_1  283067       0.376834
40                 UNKNOWN_2  241167       0.321055
41                 UNKNOWN_3  281592       0.374871

In [11]:
reports.AGE.unique()

array([ 6.20000e+01,  7.00000e+01,  8.30000e+01,  7.80000e+01,
        5.50000e+01,  6.90000e+01,  4.30000e+01,          nan,
        2.20000e+01,  9.00000e+01,  1.90000e+01,  6.00000e+01,
        4.70000e+01,  6.10000e+01,  1.70000e+01,  5.70000e+01,
        7.60000e+01,  5.40000e+01,  7.90000e+01,  7.20000e+01,
        3.90000e+01,  7.40000e+01,  8.60000e+01,  3.40000e+01,
        4.60000e+01,  3.80000e+01,  5.60000e+01,  1.50000e+01,
        5.30000e+01,  1.40000e+01,  2.90000e+01,  7.70000e+01,
        5.00000e+01,  5.80000e+01,  6.80000e+01,  4.20000e+01,
        3.20000e+01,  6.70000e+01,  4.00000e+00,  3.10000e+01,
        3.30000e+01,  3.50000e+01,  2.60000e+01,  2.30000e+01,
        2.70000e+01,  5.10000e+01,  4.00000e+01,  6.40000e+01,
        6.00000e+00,  2.10000e+01,  4.50000e+01,  2.40000e+01,
        4.80000e+01,  8.90000e+01,  3.60000e+01,  1.60000e+01,
        2.00000e+01,  1.00000e+00,  3.00000e+00,  7.50000e+01,
        7.30000e+01,  4.10000e+01,  8.00000e+01,  4.40000e+01,
        5.90000e+01,  6.50000e+01,  5.20000e+01,  1.80000e+01,
        9.00000e+00,  1.00000e+01,  4.90000e+01,  3.00000e+01,
        6.60000e+01,  5.00000e+00,  7.00000e+00,  2.80000e+01,
        3.70000e+01,  7.10000e+01,  2.50000e+01,  2.00000e+00,
        8.80000e+01,  8.40000e+01,  6.30000e+01,  1.10000e+01,
        8.20000e+01,  8.00000e+00,  8.50000e+01,  8.70000e+01,
        8.10000e+01,  1.20000e+01,  1.30000e+01,  9.10000e+01,
        9.90000e+01,  9.50000e+01,  9.20000e+01,  9.60000e+01,
        9.40000e+01,  9.30000e+01,  9.70000e+01,  9.80000e+01,
        2.50000e-01,  4.50000e+00,  1.03000e+02,  1.08000e+02,
        1.02000e+02,  1.05000e+02,  1.00000e+02,  2.38000e+02,
        1.17000e+02,  3.50000e+00,  2.50000e+00,  1.01000e+02,
        1.04000e+02,  1.60000e+00,  6.50000e+00,  1.50000e+00,
        8.50000e+00,  9.50000e+00,  5.50000e-02,  8.90000e+00,
        7.50000e+00,  2.15000e+01,  4.88000e+01,  5.75000e+01,
        6.05000e+01,  2.45000e+01,  6.10000e+00,  5.50000e+00,
        1.25000e+00,  7.60000e+00,  1.08000e+01,  1.11000e+01,
        1.16000e+01,  2.80000e+00,  3.23000e+00,  3.15000e+00,
        1.25000e+01,  4.20000e+00,  1.35000e+01,  4.70000e+00,
        1.17500e+01,  9.70000e+00,  1.63000e+01,  1.68000e+01,
        5.80000e+00,  1.79000e+01,  2.70000e+00,  4.30000e+00,
        2.86000e+00,  3.13000e+00,  1.17000e+01,  1.05000e+01,
        1.69000e+01,  1.06000e+01,  3.96000e+00,  7.85000e+01,
        1.21000e+01,  5.90000e+00,  4.11000e+01,  1.02000e+01,
        1.53000e+01,  1.34000e+01,  1.58000e+01,  1.75000e+01,
        4.80000e+00,  3.30000e+00,  2.90000e+00,  1.65000e+01,
        3.35000e+00,  1.15000e+01,  8.20000e+00,  1.29000e+01,
        4.90000e+00,  1.36000e+01,  1.90000e+00,  1.78000e+01,
        9.25000e+01,  1.32000e+01,  8.45000e+01,  7.98000e+01,
        1.09000e+01,  1.28000e+01,  6.55000e+01,  6.95000e+01,
        1.45000e+01,  1.18000e+01,  6.65000e+01,  9.76000e+02,
        8.75000e+01,  5.08330e+01,  3.70000e+00,  3.89000e+02,
        1.13000e+01,  7.75000e+01,  6.15380e+01,  6.80400e+01,
        9.80000e+00,  5.65660e+01,  6.85000e+01,  6.42180e+01,
        8.95000e+01,  8.35000e+01,  5.84000e+01,  6.49000e+01,
        8.67500e+01,  8.38510e+01,  6.61320e+01,  5.15000e+01,
        7.68000e+01,  6.15000e+02,  7.57880e+01,  3.72000e+01,
        2.00000e-01,  6.84210e+01,  7.57250e+01,  7.59420e+01,
        6.74000e+01,  1.96000e+01,  5.66000e+00,  9.22000e+00,
        6.11000e+00,  2.46000e+00,  1.15000e+02,  6.86000e+01,
        8.86000e+02,  1.55000e+01,  1.95000e+01,  6.99200e+01,
        4.55000e+01,  7.25000e+02,  6.77000e+01,  8.48000e+02,
        7.41100e+01,  6.92000e+02,  4.62000e+02,  7.43000e+02,
        9.08000e+02,  8.42000e+02,  7.82000e+02,  7.55000e+02,
        8.50000e+02,  1.80000e+00,  7.23000e+02,  3.40000e+02,
        2.93000e+02,  3.34000e+02,  8.76000e+02,  7.45000e+01,
        7.20000e+00,  1.14000e+01,  7.90000e+00,  5.00000e-01,
        5.99200e+01,  6.72500e+01,  6.61250e+01,  5.64200e+01,
        4.31700e+01,  3.25800e+01,  3.42500e+01,  7.58300e+01,
        1.83300e+01,  4.93300e+01,  2.73300e+01,  5.79200e+01,
        7.31700e+01,  7.32500e+01,  8.49200e+01,  7.59000e+01,
        6.46000e+01,  3.30800e+01,  7.39200e+01,  1.64000e+01,
        7.83000e+01,  1.09400e+01,  1.05300e+01,  1.72000e+01,
        1.07800e+01,  1.13600e+01,  1.56300e+01,  6.74000e+00,
        4.25000e+00,  8.53000e+00,  3.76000e+00,  3.80000e+00,
        6.38000e+00,  1.09200e+01,  1.18200e+01,  5.78000e+00,
        5.71000e+00,  6.30000e+00,  6.13000e+00,  8.23300e+01,
        1.80800e+01,  5.05000e+01,  2.69200e+01,  6.68000e+01,
        6.93300e+01,  5.72000e+01,  5.47500e+01,  6.61700e+01,
        8.10000e+00,  9.05000e+01,  5.72000e+00,  7.74000e+00,
        4.49000e+00,  6.77000e+00,  6.94000e+01,  6.18000e+01,
        2.63000e+02,  7.40000e+00,  6.70000e-01,  5.48000e+00,
        7.08000e+01,  3.56000e+01,  1.16900e+01,  1.16300e+01,
        9.91000e+00,  9.61000e+00,  9.63000e+00,  9.30000e+00,
        9.32000e+00,  9.60000e+00,  1.33600e+01,  2.86000e+01,
        1.11100e+01,  1.21100e+01,  4.41000e+00,  3.58000e+00,
        4.33000e+00,  7.07000e+01,  7.31000e+01,  6.67000e+01,
        4.17000e+01,  2.75000e+00,  8.27000e+02,  4.17000e+02,
        7.41000e+02,  5.20000e+00,  1.66000e+02,  3.75000e+00,
        1.06000e+02,  1.39700e+01,  1.03200e+01,  1.07200e+01,
        1.03600e+01,  1.03700e+01,  4.83000e+00,  4.67000e+00,
        1.59300e+01,  1.51800e+01,  1.56400e+01,  1.55600e+01,
        1.58200e+01,  1.78100e+01,  1.37500e+01,  1.37000e+01,
        3.82000e+00,  4.22000e+00,  4.28000e+00,  4.12000e+00,
        8.85000e+00,  7.18000e+00,  7.41000e+00,  4.99000e+01,
        3.06000e+01,  1.13000e+02,  8.38430e+01,  8.61070e+01,
        6.88070e+01,  6.81420e+01,  5.11400e+01,  4.91850e+01,
        8.34000e+02,  6.98000e+02,  7.02500e+01,  7.61630e+01,
        8.07470e+01,  9.30610e+01,  8.96030e+01,  6.90290e+01,
        5.52000e+01,  8.22990e+01,  8.46750e+01,  8.29230e+01,
        7.37130e+01,  6.42100e+01,  8.63620e+01,  6.95050e+01,
        6.39550e+01,  8.30330e+01,  7.98070e+01,  7.70670e+01,
        8.02700e+01,  6.72760e+01,  9.21000e+02,  6.86970e+01,
        4.95740e+01,  6.95790e+01,  5.26890e+01,  8.27230e+01,
        6.48750e+01,  6.73000e+02,  8.02000e+02,  8.77720e+01,
        3.09020e+01,  8.75970e+01,  6.61540e+01,  5.53230e+01,
        9.72530e+01,  8.90480e+01,  7.67630e+01,  7.35520e+01,
        6.01000e+02,  7.30000e+00,  2.40000e+00,  7.70830e+01,
        1.22000e+01,  9.00000e-01,  2.60000e+00,  5.44690e+01,
        6.45470e+01,  3.44060e+01,  8.79000e+02,  8.70900e+00,
        6.64110e+01,  6.18580e+01,  1.46750e+01,  7.15860e+01,
        6.31700e+01,  9.29000e+01,  7.51000e+02,  5.60210e+01,
        5.75790e+01,  8.65000e+02,  6.17430e+01,  6.63980e+01,
        4.74850e+01,  8.89000e+02,  9.19250e+01,  6.62720e+01,
        7.11920e+01,  9.17000e+02,  5.58000e+02,  6.65670e+01,
        5.14770e+01,  8.80370e+01,  7.69440e+01,  8.54470e+01,
        4.78160e+01,  6.35720e+01,  8.85000e+02,  3.52220e+01,
        8.84000e+02,  3.20570e+01,  6.38000e+02,  7.56950e+01,
        6.71180e+01,  6.79000e+02,  6.35060e+01,  4.64850e+01,
        6.56860e+01,  7.17940e+01,  0.00000e+00,  1.16000e+02,
        6.76600e+01,  1.19000e+01,  6.80730e+01,  5.11950e+01,
        8.15730e+01,  8.34570e+01,  8.17510e+01,  6.56370e+01,
        5.89430e+01,  7.92760e+01,  7.32310e+01,  6.01610e+01,
        5.94080e+01,  7.87000e+02,  6.58580e+01,  4.19050e+01,
        7.56130e+01,  7.59440e+01,  1.02019e+02,  7.62920e+01,
        5.02280e+01,  6.06670e+01,  8.88230e+01,  5.36120e+01,
        9.56540e+01,  8.47050e+01,  6.11000e+01,  8.40020e+01,
        8.46040e+01,  5.08910e+01,  9.64890e+01,  3.19000e+02,
        1.10770e+01,  1.74000e+02,  7.53260e+01,  6.33340e+01,
        9.31000e+02,  6.47850e+01,  8.42260e+01,  4.58170e+01,
        7.97230e+01,  2.98920e+01,  7.59960e+01,  6.54480e+01,
        7.12570e+01,  8.06430e+01,  6.15740e+01,  8.70020e+01,
        8.69560e+01,  5.17690e+01,  1.35000e+02,  8.08640e+01,
        9.16790e+01,  9.35870e+01,  9.27050e+01,  4.34000e+02,
        8.44170e+01,  7.32830e+01,  9.42000e+02,  8.28380e+01,
        8.49000e+02,  6.76490e+01,  4.61950e+01,  4.66470e+01,
        8.34930e+01,  8.46000e+02,  5.02000e+02,  7.85650e+01,
        7.09620e+01,  6.56780e+01,  5.76040e+01,  5.76310e+01,
        8.03630e+01,  8.07270e+01,  7.31820e+01,  7.54490e+01,
        8.78000e+02,  1.57000e+01,  1.70000e+00,  4.10000e+00,
        6.83610e+01,  7.50190e+01,  5.03000e+02,  5.34400e+01,
        4.77000e+02,  8.84070e+01,  7.54300e+00,  9.35800e+00,
        5.85000e+02,  8.51000e+02,  7.33190e+01,  5.10740e+01,
        5.48060e+01,  4.19000e+02,  6.39860e+01,  6.34000e+02,
        4.25570e+01,  5.67000e+01,  6.84000e+01,  4.09000e+01,
        5.43000e+01,  4.97000e+01,  7.18620e+01,  6.06560e+01,
        6.74000e+02,  7.40940e+01,  7.79160e+01,  5.46000e+02,
        3.86030e+01,  6.05930e+01,  6.62880e+01,  9.52600e+01,
        9.91580e+01,  7.72720e+01,  5.97970e+01,  6.18500e+01,
        5.82910e+01,  7.15640e+01,  6.47930e+01,  9.20000e+02,
        1.86000e+02,  6.64410e+01,  6.96060e+01,  5.23120e+01,
        6.40240e+01,  5.90000e+02,  5.88660e+01,  8.68000e+02,
        7.39210e+01,  7.69270e+01,  5.97200e+01,  7.09000e+02,
        6.33230e+01,  8.93160e+01,  7.65390e+01,  6.39800e+01,
        4.69070e+01,  6.48840e+01,  6.26800e+01,  7.33540e+01,
        7.75870e+01,  6.74600e+01,  4.10450e+01,  4.80460e+01,
        1.19000e+02,  2.03000e+02,  2.99000e+02,  5.73710e+01,
        4.42510e+01,  7.70590e+01,  9.85000e+02,  7.00750e+01,
        6.86230e+01,  6.69840e+01,  6.51850e+01,  7.34170e+01,
        7.90160e+01,  6.22120e+01,  5.23470e+01,  6.21540e+01,
        5.38670e+01,  6.55760e+01,  5.63720e+01,  7.93000e+02,
        7.38550e+01,  6.51300e+01, -6.20000e+01,  7.99280e+01,
        7.71930e+01,  6.30600e+01,  6.53050e+01,  3.47350e+01,
        7.80720e+01,  6.46320e+01, -5.60000e+01,  6.56420e+01,
        4.28060e+01,  5.58320e+01,  6.23160e+01,  6.36300e+01,
        7.33080e+01,  2.10000e+02,  7.41260e+01,  4.94180e+01,
        7.43650e+01,  7.00280e+01,  6.79200e+01])

In [12]:
reports.AGE_Y.unique()

array([ 6.20000e+01,  7.00000e+01,  8.30000e+01,  7.80000e+01,
        5.50000e+01,  6.90000e+01,  4.30000e+01,          nan,
        2.20000e+01,  9.00000e+01,  1.90000e+01,  6.00000e+01,
        4.70000e+01,  6.10000e+01,  1.70000e+01,  5.70000e+01,
        7.60000e+01,  5.40000e+01,  7.90000e+01,  7.20000e+01,
        3.90000e+01,  7.40000e+01,  8.60000e+01,  3.40000e+01,
        4.60000e+01,  3.80000e+01,  5.60000e+01,  1.50000e+01,
        5.30000e+01,  1.40000e+01,  2.90000e+01,  7.70000e+01,
        5.00000e+01,  5.80000e+01,  6.80000e+01,  4.20000e+01,
        3.20000e+01,  6.70000e+01,  4.00000e+00,  3.10000e+01,
        3.30000e+01,  3.50000e+01,  2.60000e+01,  2.30000e+01,
        2.70000e+01,  5.10000e+01,  4.00000e+01,  6.40000e+01,
        6.00000e+00,  2.10000e+01,  4.50000e+01,  2.40000e+01,
        4.80000e+01,  8.90000e+01,  3.60000e+01,  1.60000e+01,
        1.25000e+00,  2.00000e+01,  3.00000e-03,  8.00000e-03,
        8.30000e-02,  1.60000e-02,  7.50000e+01,  7.30000e+01,
        4.10000e+01,  8.00000e+01,  4.40000e+01,  5.90000e+01,
        6.50000e+01,  5.20000e+01,  1.80000e+01,  9.00000e+00,
        1.00000e+01,  4.90000e+01,  3.00000e+01,  6.60000e+01,
        5.00000e+00,  5.83000e-01,  2.80000e+01,  3.70000e+01,
        7.10000e+01,  7.00000e+00,  2.50000e+01,  7.50000e-01,
        5.00000e-03,  5.00000e-01,  8.80000e+01,  8.40000e+01,
        6.30000e+01,  1.10000e+01,  8.20000e+01,  6.67000e-01,
        1.00000e+00,  2.00000e+00,  8.50000e+01,  8.70000e+01,
        3.00000e+00,  1.83300e+00,  8.10000e+01,  5.50000e+00,
        1.20000e+01,  9.17000e-01,  2.50000e+00,  1.30000e+01,
        8.33000e-01,  4.50000e+00,  8.00000e+00,  4.17000e-01,
        9.10000e+01,  1.50000e+00,  9.90000e+01,  1.66700e+00,
        1.75000e+00,  2.50000e-01,  3.50000e+00,  3.25000e+00,
        1.67000e-01,  1.16700e+00,  9.50000e+01,  3.75000e+00,
        1.23000e-01,  9.20000e+01,  1.58300e+00,  9.60000e+01,
        1.33300e+00,  1.15000e-01,  1.08300e+00,  3.33000e-01,
        9.40000e+01,  1.92000e-01,  2.83300e+00,  1.91700e+00,
        9.30000e+01,  1.41700e+00,  1.90000e-02,  7.75000e+00,
        7.70000e-02,  3.80000e-02,  1.35000e-01,  1.10000e-02,
        5.80000e-02,  2.50000e-02,  2.16700e+00,  3.46000e-01,
        9.90000e-02,  4.83300e+00,  1.57700e+00,  9.70000e+01,
        9.80000e+01,  7.40000e-02,  4.16700e+00,  4.23000e-01,
        2.66700e+00,  5.33300e+00,  2.12000e-01,  2.33300e+00,
        2.69000e-01,  2.70000e-02,  3.30000e-02,  3.33300e+00,
        1.73000e-01,  2.31000e-01,  7.30000e-02,  3.65000e-01,
        1.54000e-01,  7.31000e-01,  6.00000e-02,  3.66700e+00,
        2.41700e+00,  2.25000e+00,  6.15000e-01,  1.40000e-02,
        3.85000e-01,  1.53000e-01,  3.41700e+00,  2.20000e-02,
        2.08300e+00,  2.58300e+00,  5.96000e-01,  9.60000e-02,
        1.97000e-01,  1.01000e-01,  5.77000e-01,  3.08000e-01,
        2.03000e-01,  5.19000e-01,  4.90000e-02,  6.41700e+00,
        6.58300e+00,  3.83300e+00,  5.58300e+00,  5.91700e+00,
        3.16700e+00,  5.16700e+00,  4.75000e+00,  4.41700e+00,
        4.91700e+00,  6.91700e+00,  2.75000e+00,  6.66700e+00,
        6.50000e+00,  5.66700e+00,  1.21200e+00,  3.60000e-02,
        2.05000e-01,  5.50000e-02,  1.38500e+00,  1.42300e+00,
        6.35000e-01,  2.36000e-01,  9.04000e-01,  1.59600e+00,
        5.38000e-01,  4.00000e-03,  1.07000e-01,  0.00000e+00,
        8.20000e-02,  4.62000e-01,  1.15400e+00,  8.08000e-01,
        3.00000e-02,  2.08000e-01,  1.75000e-01,  1.88500e+00,
        1.00000e-03,  1.61500e+00,  1.84000e-01,  1.48000e-01,
        1.40400e+00,  1.12000e-01,  4.81000e-01,  1.32000e-01,
        9.00000e-02,  1.89000e-01,  2.52000e-01,  1.10000e-01,
        1.04000e-01,  3.75000e-01,  1.03000e+02,  1.48100e+00,
        4.70000e-02,  1.08000e+02,  1.02000e+02,  6.54000e-01,
        1.51000e-01,  1.05000e+02,  1.30800e+00,  1.86000e-01,
        5.58000e-01,  1.00000e+02,  6.52000e-01,  1.00000e-02,
        2.91700e+00,  1.17000e+02,  1.26000e-01,  4.10000e-02,
        1.36500e+00,  1.09600e+00,  2.44000e-01,  1.03800e+00,
        4.04000e-01,  1.01000e+02,  6.30000e-02,  2.11000e-01,
        2.00000e-01,  5.20000e-02,  1.04000e+02,  3.91700e+00,
        3.58300e+00,  1.13500e+00,  1.60000e+00,  1.07700e+00,
        1.17300e+00,  1.46200e+00,  9.42000e-01,  1.01900e+00,
        2.82000e-01,  9.00000e-03,  2.92000e-01,  1.25000e-01,
        8.50000e+00,  9.50000e+00,  8.85000e-01,  8.90000e+00,
        7.50000e+00,  2.15000e+01,  4.88000e+01,  5.75000e+01,
        6.05000e+01,  6.73000e-01,  2.45000e+01,  6.10000e+00,
        9.30000e-02,  1.53800e+00,  3.27000e-01,  4.58000e-01,
        7.12000e-01,  1.11500e+00,  7.69000e-01,  7.60000e+00,
        1.08000e+01,  1.11000e+01,  1.16000e+01,  2.80000e+00,
        3.23000e+00,  3.15000e+00,  1.25000e+01,  4.20000e+00,
        1.35000e+01,  4.70000e+00,  1.17500e+01,  9.70000e+00,
        1.45000e-01,  1.63000e+01,  1.68000e+01,  5.80000e+00,
        1.79000e+01,  2.70000e+00,  4.30000e+00,  2.86000e+00,
        3.13000e+00,  1.17000e+01,  1.05000e+01,  1.69000e+01,
        1.06000e+01,  3.96000e+00,  7.85000e+01,  8.75000e-01,
        1.21000e+01,  1.28800e+00,  5.90000e+00,  4.11000e+01,
        1.02000e+01,  1.53000e+01,  1.34000e+01,  1.58000e+01,
        1.75000e+01,  4.80000e+00,  3.30000e+00,  2.90000e+00,
        1.65000e+01,  3.08300e+00,  6.83300e+00,  3.35000e+00,
        6.25000e-01,  9.58000e-01,  8.20000e+00,  1.29000e+01,
        9.81000e-01,  4.90000e+00,  1.36000e+01,  8.46000e-01,
        1.90000e+00,  1.78000e+01,  9.25000e+01,  1.32000e+01,
        8.45000e+01,  7.98000e+01,  1.09000e+01,  1.28000e+01,
        6.55000e+01,  6.95000e+01,  6.80000e-02,  1.51900e+00,
        1.45000e+01,  6.33300e+00,  9.62000e-01,  1.18000e+01,
        6.65000e+01,  8.13330e+01,  1.63500e+00,  6.75000e+00,
        8.75000e+01,  5.83300e+00,  5.08330e+01,  3.70000e+00,
        1.05800e+00,  4.58300e+00,  1.06600e+00,  1.13000e+01,
        1.19200e+00,  7.75000e+01,  8.27000e-01,  8.65000e-01,
        6.15380e+01,  1.26900e+00,  2.16000e-01,  1.44200e+00,
        4.08300e+00,  4.25000e+00,  6.80400e+01,  9.80000e+00,
        5.65660e+01,  5.25000e+00,  1.32700e+00,  6.92000e-01,
        1.15000e+01,  6.85000e+01,  6.42180e+01,  9.23000e-01,
        2.77000e-01,  8.95000e+01,  5.08300e+00,  8.35000e+01,
        2.41000e-01,  5.84000e+01,  6.49000e+01,  5.42000e-01,
        8.67500e+01,  8.38510e+01,  6.16700e+00,  6.61320e+01,
        5.15000e+01,  7.68000e+01,  5.12500e+01,  7.57880e+01,
        3.72000e+01,  1.70000e-01,  6.84210e+01,  6.00000e-03,
        1.21000e-01,  7.57250e+01,  7.59420e+01,  6.74000e+01,
        1.96000e+01,  5.66000e+00,  8.16700e+00,  9.22000e+00,
        6.11000e+00,  2.46000e+00,  2.25000e-01,  9.58300e+00,
        1.76900e+00,  6.86000e+01,  7.38330e+01,  1.29200e+00,
        1.95000e+01,  6.99200e+01,  4.55000e+01,  6.04170e+01,
        6.77000e+01,  7.06670e+01,  7.41100e+01,  5.76670e+01,
        5.41700e+00,  3.85000e+01,  6.19170e+01,  7.56670e+01,
        7.01670e+01,  6.51670e+01,  6.29170e+01,  7.08330e+01,
        1.80000e+00,  6.02500e+01,  2.83330e+01,  2.44170e+01,
        2.78330e+01,  7.90000e-02,  7.45000e+01,  7.20000e+00,
        1.14000e+01,  7.90000e+00,  5.99200e+01,  6.72500e+01,
        6.61250e+01,  5.64200e+01,  4.31700e+01,  3.25800e+01,
        3.42500e+01,  7.58300e+01,  1.83300e+01,  4.66700e+00,
        4.93300e+01,  2.73300e+01,  5.79200e+01,  7.31700e+01,
        7.32500e+01,  8.49200e+01,  7.59000e+01,  6.46000e+01,
        3.30800e+01,  7.39200e+01,  1.64000e+01,  7.83000e+01,
        1.09400e+01,  1.05300e+01,  1.72000e+01,  1.07800e+01,
        1.13600e+01,  1.56300e+01,  6.74000e+00,  8.53000e+00,
        3.76000e+00,  3.80000e+00,  6.38000e+00,  1.09200e+01,
        1.18200e+01,  5.78000e+00,  5.71000e+00,  6.30000e+00,
        6.13000e+00,  8.23300e+01,  1.80800e+01,  5.05000e+01,
        7.66700e+00,  2.69200e+01,  6.68000e+01,  6.93300e+01,
        5.72000e+01,  5.47500e+01,  6.61700e+01,  8.10000e+00,
        9.05000e+01,  5.72000e+00,  7.74000e+00,  4.49000e+00,
        6.77000e+00,  8.80000e-02,  6.94000e+01,  6.18000e+01,
        2.19170e+01,  7.40000e+00,  6.70000e-01,  5.48000e+00,
        7.08000e+01,  3.56000e+01,  1.16900e+01,  1.16300e+01,
        9.91000e+00,  9.61000e+00,  9.63000e+00,  9.30000e+00,
        9.32000e+00,  9.60000e+00,  1.33600e+01,  2.86000e+01,
        1.11100e+01,  1.21100e+01,  1.34600e+00,  4.41000e+00,
        3.58000e+00,  4.33000e+00,  7.07000e+01,  7.31000e+01,
        6.67000e+01,  4.17000e+01,  6.89170e+01,  3.47500e+01,
        6.17500e+01,  5.20000e+00,  1.38330e+01,  1.34000e-01,
        8.83300e+00,  1.39700e+01,  1.03200e+01,  1.07200e+01,
        1.03600e+01,  1.03700e+01,  4.83000e+00,  4.67000e+00,
        1.59300e+01,  1.51800e+01,  1.56400e+01,  1.55600e+01,
        1.58200e+01,  1.78100e+01,  1.37500e+01,  1.37000e+01,
        3.82000e+00,  4.22000e+00,  4.28000e+00,  4.12000e+00,
        8.85000e+00,  7.18000e+00,  7.41000e+00,  4.40000e-02,
        4.99000e+01,  3.06000e+01,  1.13000e+02,  8.38430e+01,
        8.61070e+01,  6.88070e+01,  6.81420e+01,  5.11400e+01,
        4.91850e+01,  5.81670e+01,  7.02500e+01,  7.61630e+01,
        8.07470e+01,  9.30610e+01,  8.96030e+01,  6.90290e+01,
        5.52000e+01,  8.22990e+01,  8.46750e+01,  8.29230e+01,
        7.37130e+01,  6.42100e+01,  8.63620e+01,  6.95050e+01,
        6.39550e+01,  8.30330e+01,  7.98070e+01,  7.70670e+01,
        8.02700e+01,  6.72760e+01,  7.67500e+01,  6.86970e+01,
        4.95740e+01,  6.95790e+01,  5.26890e+01,  8.27230e+01,
        6.48750e+01,  5.60830e+01,  6.68330e+01,  8.77720e+01,
        3.09020e+01,  8.75970e+01,  6.61540e+01,  5.53230e+01,
        9.72530e+01,  8.90480e+01,  7.67630e+01,  7.35520e+01,
        5.00830e+01,  6.08000e-01,  7.70830e+01,  1.22000e+01,
        9.00000e-01,  2.60000e+00,  5.44690e+01,  6.45470e+01,
        3.44060e+01,  8.70900e+00,  2.00000e-03,  6.64110e+01,
        6.18580e+01,  1.46750e+01,  7.15860e+01,  6.31700e+01,
        9.29000e+01,  6.25830e+01,  5.60210e+01,  5.75790e+01,
        7.20830e+01,  6.17430e+01,  6.63980e+01,  4.74850e+01,
        7.40830e+01,  9.19250e+01,  6.62720e+01,  7.11920e+01,
        7.64170e+01,  4.65000e+01,  6.65670e+01,  5.14770e+01,
        8.80370e+01,  7.69440e+01,  8.54470e+01,  4.78160e+01,
        6.35720e+01,  7.37500e+01,  3.52220e+01,  7.36670e+01,
        3.20570e+01,  5.31670e+01,  7.56950e+01,  6.71180e+01,
        5.65830e+01,  6.35060e+01,  4.64850e+01,  6.56860e+01,
        7.17940e+01,  1.16000e+02,  6.76600e+01,  1.19000e+01,
        6.80730e+01,  5.11950e+01,  8.15730e+01,  8.34570e+01,
        1.73100e+00,  8.17510e+01,  6.56370e+01,  5.89430e+01,
        7.92760e+01,  7.32310e+01,  6.01610e+01,  5.94080e+01,
        6.55830e+01,  6.58580e+01,  4.19050e+01,  7.56130e+01,
        1.15000e+02,  7.59440e+01,  1.02019e+02,  7.62920e+01,
        5.02280e+01,  6.06670e+01,  8.88230e+01,  5.36120e+01,
        9.56540e+01,  8.47050e+01,  6.11000e+01,  8.40020e+01,
        8.46040e+01,  5.08910e+01,  9.64890e+01,  8.74000e-01,
        1.10770e+01,  7.53260e+01,  6.33340e+01,  7.75830e+01,
        6.47850e+01,  8.42260e+01,  4.58170e+01,  7.97230e+01,
        2.98920e+01,  7.59960e+01,  6.54480e+01,  7.12570e+01,
        8.06430e+01,  6.15740e+01,  8.70020e+01,  8.69560e+01,
        5.17690e+01,  8.08640e+01,  9.16790e+01,  9.35870e+01,
        9.27050e+01,  3.61670e+01,  8.44170e+01,  7.32830e+01,
        8.28380e+01,  7.07500e+01,  6.76490e+01,  4.61950e+01,
        4.66470e+01,  8.34930e+01,  7.05000e+01,  4.18330e+01,
        7.85650e+01,  7.09620e+01,  6.56780e+01,  5.76040e+01,
        5.76310e+01,  8.03630e+01,  8.07270e+01,  7.31820e+01,
        7.54490e+01,  7.31670e+01,  1.57000e+01,  1.70000e+00,
        4.10000e+00,  6.83610e+01,  7.50190e+01,  4.19170e+01,
        5.34400e+01,  3.97500e+01,  8.84070e+01,  7.54300e+00,
        9.35800e+00,  4.87500e+01,  7.09170e+01,  7.33190e+01,
        5.10740e+01,  5.48060e+01,  3.49170e+01,  6.39860e+01,
        5.28330e+01,  4.25570e+01,  5.67000e+01,  6.84000e+01,
        4.09000e+01,  5.43000e+01,  4.97000e+01,  7.18620e+01,
        6.06560e+01,  5.61670e+01,  7.40940e+01,  7.79160e+01,
        3.86030e+01,  6.05930e+01,  6.62880e+01,  9.52600e+01,
        9.91580e+01,  7.72720e+01,  5.97970e+01,  6.18500e+01,
        5.82910e+01,  7.15640e+01,  6.47930e+01,  7.66670e+01,
        6.64410e+01,  6.96060e+01,  5.23120e+01,  6.40240e+01,
        4.91670e+01,  5.88660e+01,  7.23330e+01,  7.39210e+01,
        7.69270e+01,  5.97200e+01,  5.90830e+01,  7.16700e+00,
        6.33230e+01,  8.93160e+01,  8.50000e-02,  7.65390e+01,
        6.39800e+01,  4.69070e+01,  6.48840e+01,  6.26800e+01,
        7.33540e+01,  7.75870e+01,  6.74600e+01,  4.10450e+01,
        4.80460e+01,  8.41700e+00,  1.19000e+02,  2.85000e-01,
        5.56000e-01,  8.19000e-01,  5.73710e+01,  4.42510e+01,
        7.70590e+01,  8.20830e+01,  7.00750e+01,  6.86230e+01,
        6.69840e+01,  6.51850e+01,  7.34170e+01,  7.90160e+01,
        6.22120e+01,  5.23470e+01,  6.21540e+01,  5.38670e+01,
        6.55760e+01,  4.33300e+00,  5.63720e+01,  6.60830e+01,
        7.38550e+01,  6.51300e+01, -6.20000e+01,  7.99280e+01,
        7.71930e+01,  6.30600e+01,  6.53050e+01,  3.47350e+01,
        7.80720e+01,  6.46320e+01, -5.60000e+01,  6.56420e+01,
        4.28060e+01,  5.58320e+01,  6.23160e+01,  6.36300e+01,
        7.33080e+01,  7.41260e+01,  4.94180e+01,  7.43650e+01,
        7.00280e+01,  6.79200e+01])

In [13]:
reports.AGE_UNIT_ENG.unique()

array(['Years', nan, 'Months', 'Days', 'Weeks', 'Hours', 'Decade'],
      dtype=object)

In [14]:
# age is a complete mess... should fix if going to use

In [15]:
# pare down the dataset


reports = reports[['REPORT_NO', 'E2B_IMP_SAFETYREPORT_ID', 'VERSION_NO',
       'DATRECEIVED', 'DATINTRECEIVED', 'MAH_NO', 'REPORT_TYPE_CODE',
       'REPORT_TYPE_ENG', 'GENDER_CODE', 'GENDER_ENG',
       'AGE', 'AGE_Y', 'AGE_UNIT_ENG', 
       'OUTCOME_CODE', 'OUTCOME_ENG',  'WEIGHT',
       'WEIGHT_UNIT_ENG', 'HEIGHT', 'HEIGHT_UNIT_ENG',
       'SERIOUSNESS_CODE', 'SERIOUSNESS_ENG',
       'DEATH', 'DISABILITY', 'CONGENITAL_ANOMALY',
       'LIFE_THREATENING', 'HOSP_REQUIRED', 'OTHER_MEDICALLY_IMP_COND',
       'REPORTER_TYPE_ENG', 'SOURCE_CODE',
       'SOURCE_ENG', 'UNKNOWN_1', 'UNKNOWN_2', 'UNKNOWN_3']]

reports.columns.values

array(['REPORT_NO', 'E2B_IMP_SAFETYREPORT_ID', 'VERSION_NO',
       'DATRECEIVED', 'DATINTRECEIVED', 'MAH_NO', 'REPORT_TYPE_CODE',
       'REPORT_TYPE_ENG', 'GENDER_CODE', 'GENDER_ENG', 'AGE', 'AGE_Y',
       'AGE_UNIT_ENG', 'OUTCOME_CODE', 'OUTCOME_ENG', 'WEIGHT',
       'WEIGHT_UNIT_ENG', 'HEIGHT', 'HEIGHT_UNIT_ENG', 'SERIOUSNESS_CODE',
       'SERIOUSNESS_ENG', 'DEATH', 'DISABILITY', 'CONGENITAL_ANOMALY',
       'LIFE_THREATENING', 'HOSP_REQUIRED', 'OTHER_MEDICALLY_IMP_COND',
       'REPORTER_TYPE_ENG', 'SOURCE_CODE', 'SOURCE_ENG', 'UNKNOWN_1',
       'UNKNOWN_2', 'UNKNOWN_3'], dtype=object)

## 2. report_drug.txt

In [16]:
report_drug = pd.read_csv(data_dir + '/report_drug.txt', 
                      delimiter='$', 
                      header=None, 
                      names=['REPORT_DRUG_ID', 'REPORT_ID', 'DRUG_PRODUCT_ID', 'DRUGNAME', 'DRUGINVOLV_ENG', 'DRUGINVOLV_FR', 'ROUTEADMIN_ENG', 'ROUTEADMIN_FR', 'UNIT_DOSE_QTY', 'DOSE_UNIT_ENG', 'DOSE_UNIT_FR', 'FREQUENCY', 'FREQ_TIME', 'FREQUENCY_TIME_ENG', 'FREQUENCY_TIME_FR', 'FREQ_TIME_UNIT_ENG', 'FREQ_TIME_UNIT_FR', 'THERAPY_DURATION', 'THERAPY_DURATION_UNIT_ENG', 'THERAPY_DURATION_UNIT_FR', 'DOSAGEFORM_ENG', 'DOSAGEFORM_FR'],
                      dtype={'REPORT_DRUG_ID': 'object', 'REPORT_ID': 'object', 'DRUG_PRODUCT_ID': 'object', 'DRUGNAME': 'object', 'DRUGINVOLV_ENG': 'object', 'DRUGINVOLV_FR': 'object', 'ROUTEADMIN_ENG': 'object', 'ROUTEADMIN_FR': 'object', 'UNIT_DOSE_QTY': 'float64', 'DOSE_UNIT_ENG': 'object', 'DOSE_UNIT_FR': 'object', 'FREQUENCY': 'float64', 'FREQ_TIME': 'float64', 'FREQUENCY_TIME_ENG': 'object', 'FREQUENCY_TIME_FR': 'object', 'FREQ_TIME_UNIT_ENG': 'object', 'FREQ_TIME_UNIT_FR': 'object', 'THERAPY_DURATION': 'float64', 'THERAPY_DURATION_UNIT_ENG': 'object', 'THERAPY_DURATION_UNIT_FR': 'object', 'DOSAGEFORM_ENG': 'object', 'DOSAGEFORM_FR': 'object'}
                     )

In [17]:
report_drug.dtypes

REPORT_DRUG_ID                object
REPORT_ID                     object
DRUG_PRODUCT_ID               object
DRUGNAME                      object
DRUGINVOLV_ENG                object
DRUGINVOLV_FR                 object
ROUTEADMIN_ENG                object
ROUTEADMIN_FR                 object
UNIT_DOSE_QTY                float64
DOSE_UNIT_ENG                 object
DOSE_UNIT_FR                  object
FREQUENCY                    float64
FREQ_TIME                    float64
FREQUENCY_TIME_ENG            object
FREQUENCY_TIME_FR             object
FREQ_TIME_UNIT_ENG            object
FREQ_TIME_UNIT_FR             object
THERAPY_DURATION             float64
THERAPY_DURATION_UNIT_ENG     object
THERAPY_DURATION_UNIT_FR      object
DOSAGEFORM_ENG                object
DOSAGEFORM_FR                 object
dtype: object

In [18]:
report_drug.nunique()

REPORT_DRUG_ID               2860848
REPORT_ID                     751107
DRUG_PRODUCT_ID                44794
DRUGNAME                       34634
DRUGINVOLV_ENG                     5
DRUGINVOLV_FR                      5
ROUTEADMIN_ENG                    72
ROUTEADMIN_FR                     72
UNIT_DOSE_QTY                   3426
DOSE_UNIT_ENG                     53
DOSE_UNIT_FR                      53
FREQUENCY                         62
FREQ_TIME                         73
FREQUENCY_TIME_ENG                12
FREQUENCY_TIME_FR                 12
FREQ_TIME_UNIT_ENG               526
FREQ_TIME_UNIT_FR                526
THERAPY_DURATION                1857
THERAPY_DURATION_UNIT_ENG         11
THERAPY_DURATION_UNIT_FR          11
DOSAGEFORM_ENG                   374
DOSAGEFORM_FR                    366
dtype: int64

In [19]:
report_drug.tail(3)

,REPORT_DRUG_ID,REPORT_ID,DRUG_PRODUCT_ID,DRUGNAME,DRUGINVOLV_ENG,DRUGINVOLV_FR,ROUTEADMIN_ENG,ROUTEADMIN_FR,UNIT_DOSE_QTY,DOSE_UNIT_ENG,DOSE_UNIT_FR,FREQUENCY,FREQ_TIME,FREQUENCY_TIME_ENG,FREQUENCY_TIME_FR,FREQ_TIME_UNIT_ENG,FREQ_TIME_UNIT_FR,THERAPY_DURATION,THERAPY_DURATION_UNIT_ENG,THERAPY_DURATION_UNIT_FR,DOSAGEFORM_ENG,DOSAGEFORM_FR
2860845,2634355,902722186,16706,METHOTREXATE,Concomitant,Concomitant,Unknown,Inconnu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NOT SPECIFIED,NON PRÉCISÉE
2860846,2628946,902722533,28639,STELARA,Suspect,Suspect,Subcutaneous,Subcutaneux,90.0,Milligram,Milligramme,1.0,4.0,Weeks,Semaine(s),1 every 4 Weeks,1 chaque 4 Semaine(s),NaN,NaN,NaN,SOLUTION SUBCUTANEOUS,SOLUTION POUR ADMINISTRATION SOUS-CUTANÉE
2860847,2642632,902722572,33294,BORTEZOMIB,Suspect,Suspect,Subcutaneous,Subcutaneux,2.7,Milligram,Milligramme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Injection,Injectable

In [20]:
report_drug[report_drug['REPORT_ID']=='902816047']

,REPORT_DRUG_ID,REPORT_ID,DRUG_PRODUCT_ID,DRUGNAME,DRUGINVOLV_ENG,DRUGINVOLV_FR,ROUTEADMIN_ENG,ROUTEADMIN_FR,UNIT_DOSE_QTY,DOSE_UNIT_ENG,DOSE_UNIT_FR,FREQUENCY,FREQ_TIME,FREQUENCY_TIME_ENG,FREQUENCY_TIME_FR,FREQ_TIME_UNIT_ENG,FREQ_TIME_UNIT_FR,THERAPY_DURATION,THERAPY_DURATION_UNIT_ENG,THERAPY_DURATION_UNIT_FR,DOSAGEFORM_ENG,DOSAGEFORM_FR
1399788,2831149,902816047,11237,FAMPYRA,Suspect,Suspect,Oral,Oral,10.0,Milligram,Milligramme,2.0,1.0,Days,Jour(s),2 every 1 Days,2 chaque 1 Jour(s),NaN,NaN,NaN,TABLET (EXTENDED-RELEASE),COMPRIMÉ (LIBÉRATION PROLONGÉE)

In [21]:
# Check if REPORT_NO is in REPORT_ID

print('count of REPORT_NO:', reports['REPORT_NO'].count())
print('count of unique REPORT_NO:', reports['REPORT_NO'].nunique())
print('count of REPORT_NO in REPORT_ID:', reports['REPORT_NO'].isin(report_drug['REPORT_ID']).count())

count of REPORT_NO: 751171
count of unique REPORT_NO: 751171
count of REPORT_NO in REPORT_ID: 751171

In [22]:
# pare down report_drug

report_drug = report_drug[['REPORT_DRUG_ID', 'REPORT_ID', 'DRUG_PRODUCT_ID', 'DRUGNAME',
       'DRUGINVOLV_ENG', 'ROUTEADMIN_ENG',
        'UNIT_DOSE_QTY', 'DOSE_UNIT_ENG', 
       'FREQUENCY', 'FREQ_TIME', 'FREQUENCY_TIME_ENG',
        'FREQ_TIME_UNIT_ENG', 
       'THERAPY_DURATION', 'THERAPY_DURATION_UNIT_ENG',
        'DOSAGEFORM_ENG']]

# import the rest

In [23]:
# import drug_products, drug_product_ingredients, and reactions

drug_products = pd.read_csv(data_dir + '/drug_products.txt', 
                            delimiter='$',
                            header = None,
                            names = ['DRUG_PRODUCT_ID','DRUGNAME'],
                            dtype = {'DRUG_PRODUCT_ID':'object','DRUGNAME':'object'})

drug_product_ingredients = pd.read_csv(data_dir + '/drug_product_ingredients.txt', 
                            delimiter='$',
                            header = None,
                            names = ['DRUG_PRODUCT_INGREDIENT_ID','DRUG_PRODUCT_ID','DRUGNAME','ACTIVE_INGREDIENT_ID','ACTIVE_INGREDIENT_NAME'],
                            dtype = {'DRUG_PRODUCT_INGREDIENT_ID':'object', 'DRUG_PRODUCT_ID':'object','ACTIVE_INGREDIENT_ID':'object'})


reactions = pd.read_csv(data_dir + '/reactions.txt', 
                            delimiter='$',
                            header = None,
                            names = ['REACTION_ID','REPORT_ID','DURATION','DURATION_UNIT_ENG','DURATION_UNIT_FR','PT_NAME_ENG','PT_NAME_FR','SOC_NAME_ENG','SOC_NAME_FR','MEDDRA_VERSION'],
                            dtype = {'REACTION_ID':'object','REPORT_ID':'object'})

C:\Users\lt\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [24]:
drug_products.dtypes

DRUG_PRODUCT_ID    object
DRUGNAME           object
dtype: object

In [25]:
drug_products.head(3)

  DRUG_PRODUCT_ID                      DRUGNAME
0               1  PATENT BLUE SODIUM INJECTION
1               2            KCL SOLUTION A 20%
2               3             QUINATE TAB 325MG

In [26]:
drug_products.nunique()

DRUG_PRODUCT_ID    44834
DRUGNAME           34634
dtype: int64

In [27]:
drug_products.groupby('DRUGNAME').count().sort_values(by='DRUG_PRODUCT_ID', ascending=False)

                                                    DRUG_PRODUCT_ID
DRUGNAME
VITAMIN D3                                                       24
ROSUVASTATIN                                                     22
ATENOLOL                                                         21
PREGABALIN                                                       20
VENLAFAXINE XR                                                   19
...                                                             ...
EXTRA STRENGTH TYLENOL SINUS PAIN AND CONGESTIO...                1
EXTRA STRENGTH TYLENOL SINUS PAIN AND CONGESTIO...                1
EXTRA STRENGTH TYLENOL SINUS NIGHTTIME                            1
EXTRA STRENGTH TYLENOL SINUS DAYTIME                              1
ÉCRAN SOLAIRE À VAPORISATION CONTINUE POUR ENFA...                1

[34634 rows x 1 columns]

In [28]:
drug_product_ingredients.dtypes

DRUG_PRODUCT_INGREDIENT_ID    object
DRUG_PRODUCT_ID               object
DRUGNAME                      object
ACTIVE_INGREDIENT_ID          object
ACTIVE_INGREDIENT_NAME        object
dtype: object

In [29]:
drug_product_ingredients.head()

,DRUG_PRODUCT_INGREDIENT_ID,DRUG_PRODUCT_ID,DRUGNAME,ACTIVE_INGREDIENT_ID,ACTIVE_INGREDIENT_NAME
0,8193011772,8193,NOVO-BUPROPION SR TABLETS,11772,bupropion hydrochloride
1,8207042,8207,"BALANCE 1.5% GLUCOSE, 1.25MMOL/L CALCIUM",42,dextrose
2,8218010247,8218,TYLENOL COUGH,10247,dextromethorphan hydrobromide
3,822904182,8229,SANDOZ-CARBAMAZEPINE CR,4182,carbamazepine
4,727404803,7274,PREGVIT FOLIC 4,4803,calcium

In [30]:
drug_product_ingredients.nunique()

DRUG_PRODUCT_INGREDIENT_ID    297780
DRUG_PRODUCT_ID                30847
DRUGNAME                       22690
ACTIVE_INGREDIENT_ID           20110
ACTIVE_INGREDIENT_NAME         17631
dtype: int64

In [31]:
reactions.dtypes

REACTION_ID           object
REPORT_ID             object
DURATION             float64
DURATION_UNIT_ENG     object
DURATION_UNIT_FR      object
PT_NAME_ENG           object
PT_NAME_FR            object
SOC_NAME_ENG          object
SOC_NAME_FR           object
MEDDRA_VERSION        object
dtype: object

In [32]:
reactions.head()

,REACTION_ID,REPORT_ID,DURATION,DURATION_UNIT_ENG,DURATION_UNIT_FR,PT_NAME_ENG,PT_NAME_FR,SOC_NAME_ENG,SOC_NAME_FR,MEDDRA_VERSION
0,13501,135,NaN,NaN,NaN,Dysuria,Dysurie,Renal and urinary disorders,Affections du rein et des voies urinaires,v.22.1
1,13502,135,NaN,NaN,NaN,Nocturia,Nycturie,Renal and urinary disorders,Affections du rein et des voies urinaires,v.22.1
2,13601,136,NaN,NaN,NaN,Nausea,Nausée,Gastrointestinal disorders,Affections gastro-intestinales,v.22.1
3,13701,137,NaN,NaN,NaN,Headache,Céphalée,Nervous system disorders,Affections du système nerveux,v.22.1
4,13801,138,NaN,NaN,NaN,Pruritus,Prurit,Skin and subcutaneous tissue disorders,Affections de la peau et du tissu sous-cutané,v.22.1

In [33]:
reactions.nunique()

REACTION_ID          2606282
REPORT_ID             750583
DURATION                1593
DURATION_UNIT_ENG          9
DURATION_UNIT_FR           9
PT_NAME_ENG            11993
PT_NAME_FR             11993
SOC_NAME_ENG              27
SOC_NAME_FR               27
MEDDRA_VERSION             1
dtype: int64

# check wheter ACTIVE_DRUG_NAME is linkable to DrugBank

In [36]:
db_vocab = pd.read_csv(data_dir + '/DrugBank/drugbank vocabulary.csv')

In [37]:
db_vocab.head(3)

,DrugBank ID,Accession Numbers,Common name,CAS,UNII,Synonyms,Standard InChI Key
0,DB00001,BIOD00024 | BTD00024,Lepirudin,138068-37-8,Y43GF64R34,Hirudin variant-1 | Lepirudin recombinant,NaN
1,DB00002,BIOD00071 | BTD00071,Cetuximab,205923-56-4,PQX0D8J21J,Cetuximab | Cétuximab | Cetuximabum | Immunogl...,NaN
2,DB00003,BIOD00001 | BTD00001,Dornase alfa,143831-71-4,953A26OA1Y,Deoxyribonuclease (human clone 18-1 protein mo...,NaN

In [42]:
db_vocab.nunique()

DrugBank ID           13475
Accession Numbers      4443
Common name           13475
CAS                    7773
UNII                   9127
Synonyms               5818
Standard InChI Key    10694
dtype: int64

In [39]:
drug_product_ingredients = pd.read_csv(data_dir + '/drug_product_ingredients.txt',
                                       delimiter='$', 
                                      header=None, 
                                      names=['DRUG_PRODUCT_INGREDIENT_ID','DRUG_PRODUCT_ID', 'DRUGNAME', 'ACTIVE_INGREDIENT_ID', 'ACTIVE_INGREDIENT_NAME']
                                      )

In [40]:
drug_product_ingredients.head()

,DRUG_PRODUCT_INGREDIENT_ID,DRUG_PRODUCT_ID,DRUGNAME,ACTIVE_INGREDIENT_ID,ACTIVE_INGREDIENT_NAME
0,8193011772,8193,NOVO-BUPROPION SR TABLETS,11772,bupropion hydrochloride
1,8207042,8207,"BALANCE 1.5% GLUCOSE, 1.25MMOL/L CALCIUM",42,dextrose
2,8218010247,8218,TYLENOL COUGH,10247,dextromethorphan hydrobromide
3,822904182,8229,SANDOZ-CARBAMAZEPINE CR,4182,carbamazepine
4,727404803,7274,PREGVIT FOLIC 4,4803,calcium

In [41]:
drug_product_ingredients.nunique()

DRUG_PRODUCT_INGREDIENT_ID    297780
DRUG_PRODUCT_ID                30847
DRUGNAME                       22690
ACTIVE_INGREDIENT_ID           20110
ACTIVE_INGREDIENT_NAME         17631
dtype: int64

In [48]:
drug_product_ingredients[drug_product_ingredients.ACTIVE_INGREDIENT_NAME.isin(db_vocab['Common name'].str.capitalize())]

,DRUG_PRODUCT_INGREDIENT_ID,DRUG_PRODUCT_ID,DRUGNAME,ACTIVE_INGREDIENT_ID,ACTIVE_INGREDIENT_NAME
11362,2194505000244,21945,7-HYDROXYSTAUROSPORINE,5000244,7-hydroxystaurosporine
17039,1584307003199,15843,T-ALPHA,7003199,"3,3'-diindolylmethane"
26216,1509207003199,15092,DIM ENHANCED,7003199,"3,3'-diindolylmethane"
31602,3773007003199,37730,DIINDOLYLMETHANE,7003199,"3,3'-diindolylmethane"
37900,3073107003199,30731,ESTROSMART,7003199,"3,3'-diindolylmethane"
...,...,...,...,...,...
285386,2353005006751,23530,VAGIFEM,5006751,2-methoxyestradiol
286943,2006405006751,20064,ESTRADOT,5006751,2-methoxyestradiol
290424,1217905006751,12179,LUPIN-ESTRADIOL,5006751,2-methoxyestradiol
294541,2715005006751,27150,ESTRADIOL/MEDROXYPROGESTERONE,5006751,2-methoxyestradiol
296161,2807305006751,28073,ESTROGEN NOS,5006751,2-methoxyestradiol